# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d688a542e170ed5445d63d19cb2a398ae9073e60e79abae7b7b27f2d3d9482edaa991765f562b188978cad5a83b93301b7df4e6cffc7bba3ce475b023277d696

test:
  secret_key_base: 7b991246595415464ddec1678a33a256d5ebc160e01525d320b3d1f1d4338a27912b862c6d2638c9688c03f48ae2f8627622d275b41944df5c3114981e09ba35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
